MODEL:
    hidden_size: 128

TRAINARGS:
    use_gpu: true
    train_batch_size: 2
    eval_batch_size: 2
    epochs: 1000
    eval_epoch: 10
    signature:
        x: 
            shape: 
                - null
            type: float32
        labels: 
            shape: 
                - null
            type: float32

    checkpoint_dir: checkpoint
    save_epoch: 50
    save_total_limit: 10

    logging_dir: log
    logging_steps: 10
    logging_print: false

    learning_rate: 0.0001
    warmup_steps: 4000
    adam_beta1: 0.9
    adam_beta2: 0.98
    adam_epsilon: 0.000000001

# datasets feild. Set the parameters for your custom dataset.
DATASETS:
    train_data_path: train_data.json
    eval_data_path: test_data.json
    train_test_split: null
    worker: 1
    batch_size: 1000
    shuffle_seed: null

# disable hydra logging.
hydra:
  run:
    dir: . 
  output_subdir: null
  job_logging: null
  hydra_logging: null

# etc feild and user custom feild
ETC:
    output_dir: model